django_auth/default_auth/urls.py
from django.urls import path
from . import views

app_name = 'default_auth'
urlpatterns = [
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('dashboard/', views.Dashboard, name="dashboard"),
    path('logout/', views.Logout, name="logout"),
    path('login/', views.LoginView.as_view(), name="login"),

]

django_auth/django_auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('default_auth/',include('default_auth.urls')),

]

django_auth/default_auth/models.py
from django.db import models

# Create your models here.

django_auth/default_auth/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User


class SignupForm(ModelForm):
    """user signup form"""
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password', 'email',)


class LoginForm(forms.Form):
    """user login form"""
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

django_auth/default_auth/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm, LoginForm
from django.views.generic.edit import FormView
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages


class SignupView(FormView):
    template_name = 'default_auth/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('default_auth:dashboard')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = True
        user.save()

        login(self.request, user)

        return HttpResponseRedirect(self.get_success_url())


def Dashboard(request):
    return render(request, 'default_auth/dashboard.html')


def Logout(request):
    """logout logged in user"""
    logout(request)
    return redirect(reverse_lazy('default_auth:dashboard'))


class LoginView(FormView):
    """ login view"""
    template_name = 'default_auth/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('default_auth:dashboard')

    def form_valid(self, form):
        post_data = form.cleaned_data
        user = authenticate(username=post_data['username'],
                            password=post_data['password'])
        if user is not None:
            login(self.request, user)
        else:
            messages.add_message(self.request, messages.INFO, 'Wrong credentials.\
                    Please try again with correct input')
            return HttpResponseRedirect(reverse_lazy('default_auth:login'))

        return HttpResponseRedirect(reverse_lazy('default_auth:dashboard'))

django_auth/templates/default_auth/dashboard.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
{% if request.user.is_authenticated %}
<h1>Congratulations!! You are now logged In dear {{request.user.username}} </h1>
<div class="">
<button type="button" name="button"><a href="{% url 'default_auth:logout' %}">Logout</a></button>
</div>
{% else %}
<h1>You Are Not logged in. Access Denied</h1>
{%endif%}
  </body>
</html>

django_auth/templates/default_auth/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
      {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
      {% endfor %}
  </ul>
{% endif %}
    <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="signup" value="Signup">
    </form>
  </body>
</html>

django_auth/templates/default_auth/signup.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="signup" value="Signup">
    </form>
  </body>
</html>